server:
  port: 8083
spring:
  application:
    name: PRODUCT_SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/product_service_db
    password: 7777

    driver-class-name: org.postgresql.Driver




  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

services:
  inventory-url: http://INVENTORY-SERVICE/inventory
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true
