server:
  port: 8085
spring:
  application:
    name: PRODUCT_SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/product_service_db
    password: 1106

    driver-class-name: org.postgresql.Driver




  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

services:
  inventory-url: http://INVENTORY-SERVICE/inventory
eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA_URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848

